### ISSUE TITLE
where are the screenshots?

### ISSUE THREAD

**Issue by gregwebs** [joshbuddy/ghostbuster#10]
```
  ✗ Simple index
    Assert first for selector p did not meet expectations

0 success, 1 failure, 0 pending
Copying screenshots ✓
Stopping server ✓
Cleaning up temporary screenshots ✓
```

How do I see the screenshots or prevent it from cleaning up the screenshots?
Or are there no screenshots? I see folders in /tmp, but no screenshots.

**Comment by joshbuddy** [comment]
It only creates screenshots if the test has no failures. I fixed it up so it doesn't report "Copying screenshots" when it's really not. If there is a real use, we could have it copy over the screen shots when it's been unsuccessful... tell more about what you're doing.

**Comment by gregwebs** [comment]
So i am still trying to learn how to use this. I was thinking it would actually be more useful to see a screenshot on a failure. Previously when i have ran these kinds of tests (env-js) I would often want to print out more context and often even dump the html for the page and view it in the browser. I am wondering too if there is some kine of API at my disposal to take a screenshot and/or dump the page html.

**Comment by gregwebs** [comment]
So i am using this a bit more and i definitely want screenshots just on failure and it would also be nice to have the ability to create a screenshot on demand.

**Comment by joshbuddy** [comment]
Yeah, I realize you're probably correct. It would be good to output those failed screenshots somewhere. But they can't be copied into your normal directory. Where do you think they should go?

**Comment by gregwebs** [comment]
Can't they go into the screenshots_dir?

**Comment by gregwebs** [comment]
I sent a pull request, but I am still seeing a screenshot when the test reports no failures- seems like it is taking a picture of the initial page request.
