### ISSUE TITLE
0.2.1 doesn't work on osx 10.6.8

### ISSUE THREAD

**Issue by optixx** [joshbuddy/ghostbuster#2]
<pre>
[david@box] ~ % sudo gem install ghostbuster                                                                                                                                  [8489]
Successfully installed ghostbuster-0.2.1
1 gem installed
Installing ri documentation for ghostbuster-0.2.1...
Installing RDoc documentation for ghostbuster-0.2.1...
[david@box] ~ % rehash                                                                                                                                                        [8490]
[david@box] ~ % ghostbuster                                                                                                                                                   [8491]
/Library/Ruby/Gems/1.8/gems/ghostbuster-0.2.1/lib/ghostbuster.rb:11:in `exist?': can't convert nil into String (TypeError)
    from /Library/Ruby/Gems/1.8/gems/ghostbuster-0.2.1/lib/ghostbuster.rb:11:in `initialize'
    from /Library/Ruby/Gems/1.8/gems/ghostbuster-0.2.1/lib/ghostbuster/runner.rb:13:in `new'
    from /Library/Ruby/Gems/1.8/gems/ghostbuster-0.2.1/lib/ghostbuster/runner.rb:13:in `run'
    from /Library/Ruby/Gems/1.8/gems/ghostbuster-0.2.1/bin/ghostbuster:4
    from /usr/bin/ghostbuster:19:in `load'
    from /usr/bin/ghostbuster:19
</pre>

**Comment by joshbuddy** [comment]
Fixed in 0.2.2

**Comment by optixx** [comment]
ACK. Thx
