### ISSUE TITLE
start/stop

### ISSUE THREAD

**Issue by gregwebs** [joshbuddy/ghostbuster#9]
I am running on linux. I have no tests yet. I created a start script:

``` bash
#!/bin/bash

cd ..
exec bundle exec unicorn -E test -p 3333 &
```

I also have a shutdown script. When I run `ghostbuster`, all I see is a constant spinner and the command never finishes.

```
Starting server \
```

I am probably missing something because I am really tired and about to go to sleep now :)

**Comment by joshbuddy** [comment]
Can you show me a little more about your directory layout? Does executing start.sh work normally? I can definitely put some more error output here as well. I will do that now.

**Comment by gregwebs** [comment]
yes, start & stop work fine without ghostbuster. I am wondering if is
simpler to have an option of letting me start & stop my test app and launch
ghostbuster rather than ghostbuster always be expected to launch my app. I
will try to accomplish this now with noop scripts for start & stop.

**Comment by joshbuddy** [comment]
This ... surprises me. Hm. Any chance you can make a repo of your barebones start/stop so I can take a look at it in more detail?

**Comment by gregwebs** [comment]
have you tried with unicorn yet?

I am doing fine with empty scripts for start and stop and launching ghostbuster myself

**Comment by gregwebs** [comment]
rails s works fine in the start script

**Comment by gregwebs** [comment]
oh, never mind- i can't get rails s to unblock either.

**Comment by gregwebs** [comment]
isn't the optimal solution to run the request through memory instead of over a TCP server? The same way integration testing is normally done. When loading the code up it should be very clear when that is done, unlike when launching a web server. This would eliminate the start & stop hassle and overall be much more efficient.

**Comment by gregwebs** [comment]
oh, by the way, I was having problems with my external ghostbuster runner timing out for the first request. But now I put in a curl call to the app in my script that runs before running the tests and everything is working.

**Comment by gregwebs** [comment]
So in terms of running the request through memory i don't know if is an easy way to do that from phantom.js. If not you would still need your own server that catches the browser requests and then hands them off to the application, so maybe that is not much better.

**Comment by joshbuddy** [comment]
I think over HTTP and TCP is best at this point. These are supposed to be real integration tests.. certainly simplest. I think the problem with your starting and stopped scripts is the way you're daemonizing unicorn. Try using -D for daemonizing ... and --pid for the pid file location.

**Comment by gregwebs** [comment]
-D does allow the tests to start. However, i always get a timeout, even when
putting in a sleep or an initial warmup curl requests

```
The request for http://localhost:3333/ timed out
```

The point of a "real integration" test is that it exercises the entire
application stack with a full browser experience. I don't write what Rails
calls functional tests because they don't exercise the entire application
stack. But I have always liked writing integration tests (or what rspec
calls requests tests) with Capybara that do exercise the entire stack. The
part that has always been missing there is the full browser experience.

**Comment by gregwebs** [comment]
oh, nevermind- the -D seems to be working just fine. I do have to put an initial curl after starting up the server- the curl has the effect of actually waiting for the server to be ready.
